spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: yungbo
    password: yungbo

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernamte:
        format_sql: ture

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

custom:
  path:
    upload-images: 'C:/dev/uploadSaveTest/'



