spring:
  datasource:
    url: jdbc:mariadb://database-1.cmhfqce0eopv.ap-northeast-2.rds.amazonaws.com:3306/test
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    driver-class-name: org.h2.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: guseo101
  messages:
    basename=messages,errors:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernamte:
        format_sql: true



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

custom:
  path:
    upload-images: C:\dev\uploadSaveTest
#    여기에 업로드 한 이미지들 저장되고, 불러옴.



